### ISSUE TITLE
Error with qwik 1.1.5

### ISSUE THREAD

**Issue by genox** [NexonTreeHouse/qwik-graphql-client#4]
Hi,

Trying to use the client, I get the following error:

```
[q] 9:23:46 AM [vite] Internal server error: Dynamic require of "null.js" is not supported
...
[q]       at AsyncFunction.GraphQLClientProvider_component_useTask_S0wzgaltP98 (/.../node_modules/qwik-graphql-client/lib/index.qwik.mjs:11084:48)
...

```

Not sure what to do, but it points to a non-serialisable value provided, probably the Provider:

```tsx
        <GraphQLClientProvider
          clientGenerator$={() =>
            new ApolloClient({
              cache: new InMemoryCache(),
              uri: saleorApiUrl,
            })
          }>
```

On second thought, this seems like an anti-pattern to what qwik wants us to do, like avoiding pushing anything but serialisable, simple data into component$'s.

Did you test this with the latest qwik version?

edit: just tried without using the context provider and providing `clientGenerator$` directly in the component, but I get an error as well, referring to a missing context:

```
[q] 9:43:30 AM [vite] Internal server error: Code(13): Actual value for useContext() can not be found, make sure some ancestor component has set a value using useContextProvider()
```

**Comment by genox** [comment]
Ah, it looks like the anonymous function in the parameter of the provider component needs to be wrapped with a dollar function in order for it to work. I copy/pasted from the example in the readme.md.

**Comment by NexonTreeHouse** [comment]
I have pushed out a quick fix to allow generating clients in the `useLazyQuery` and the `useMutation` hooks outside of a client provider. Doing so in a `useQuery` won't work the current way everything is set up and requires a bit more thought on how to implement that. 

The issue is that `useQuery` returns a resource so the return must be done in the root of the hook. Thereby returning different resources depending on if a clientGenerator$ is passed in can not be done easily.

**Comment by genox** [comment]
I got it to work. all fine :) thank you.
